name: windows
#on: [push, pull_request]
on:
  push:
    # run only against tags
    tags:
      - '*'
jobs:

  build:
    name: build
    runs-on: [ windows-latest ]
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure
    
    - name: Create ZIP file
      run: |
        # 导航到你的项目目录（如果需要）
        cd D:\a\nanomsg\nanomsg\build
        # 创建一个ZIP文件，包括你想要打包的文件和目录
        7z a -tzip 1.zip *
        dir 
      
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: D:\a\nanomsg\nanomsg\build\1.zip
